### PR TITLE
Allow DanmakuPrefabs to set which layer they collide against

### PR DESCRIPTION
**Pull request by TotallyGatsby**
Right now, I don't believe that DanmakuPool.CollisionMasks is ever set. There's a lot of ways to solve this, but this seems like a relatively straightforward one -- Danmaku created from a pool all collide against the same layers.

### CODE REVIEW

**Comment by TotallyGatsby** [comment]
Wasn't sure if you wanted to actually implement per danmaku collision masks, but this at least makes it possible to create danmaku with different layer masks in the interim. (Also, feel free to toss this out if you think that there's a better approach.)

**Comment by crazoter** [comment]
I've only started using this repo for a few hours, so take what I say with a pinch of salt ;)

I think the change can (or perhaps should?) be applied to DanmakuEmitter. As it is now if you apply the change to DanmakuPrefabs, you'll need a different prefab for each layer you want your bullets to be in, but if you apply the change to the DanmakuEmitter, you simply need a different emitter to apply the layer.

The pros of doing that would be more flexibility and also removes the need of multiple prefabs. The con is that you'll need to define the layer for each emitter you use/create.

**Comment by TotallyGatsby** [comment]
That sounds reasonable to me. Thoughts @james7132 ?

**Comment by james7132** [comment]
I'm of the general opinion that we should try to mimic or map a subset of GameObject like features as much as possible, namely the ability to use the GameObject level layer field in DanmakuPrefabs to change the basic collision behavior. This keeps it consistent for designers who are used to dealing with normal prefabs. I was meaning to do this, but I don't think I ever got around to implementing it (though the vestiges of the idea do remain).

I do like the idea of allowing per-Danmaku collision control. It should allow for powerful control over use-cases like temporarily disabling collisions against certain groups of colliders depending on some game state. 

DanmakuEmitter isn't meant to be the end-all-be-all of firing bullets, but a good prototyping base. The real power of the library comes from the low-level scripting of bullet patterns. In my opinion, it should be best if we found a way to allow the use of defaults (as mentioned by the idea behind DanmakuPrefab) and then expose ways to override this in an intelligent way at that level, then propagating it up to the DanmakuEmitter level seems to be a better approach.

**Comment by TotallyGatsby** [comment]
Makes total sense. I'll try to wire up the Layer of the DanmakuPrefab such that the layer sets collision mask for the Danmaku. That way the default behavior will be to behave like any other Unity gameobject (but as a dev you could possibly override it somehow.)

**Comment by crazoter** [comment]
I was thinking of layers as another variable of bullets, like how the color of the bullet was "defined" in the emitter instead of the prefab. Following that line of thought, it made more sense to put the layer (and by extension the layermask) in the emitter than the prefab. 

If you consider that some bullet hell games may play around with the layering system e.g. blue for collide with blue layer, red for collide with red layer etc, it made more sense to put it in the emitter as well.

But I'm also aware that the emitter is supposed to be more focused on the bullet hell pattern creation rather than layering, so I think it's more of a design decision. So long as implementation supports the goals of the developer, I think it's okay either way (although, I'm lazy to create multiple prefabs when I can just declare the layer in the emitter instead).

Implementation-wise, I think here's how it could go:
In DanmakuEmitter:
```
//Variable declaration
public int initialLayer = 0; //For Unity Inspector

  protected int layerMask = 0;//The layermask to be used
  protected int gameObjectLayer = 0;
  public int layer {
    get {return gameObjectLayer;}
    set {
      gameObjectLayer = value;
      layerMask = 1 << gameObjectLayer;
    }
  }
...
void Start() {
...
//Pass layermask into CreateSet
...
}
```
gameObjectLayer can be replaced with initialLayer, but I separated them for clarity purposes in this gist.
initialLayer is public for the Unity Inspector (you can't set values via the Inspector using variables declared with getters and setters).

This change would suffice for a quick fix, but for a more comprehensive fix (and to allow for changing of layers after initialization), we'll have to refer to how Danmaku's color is implemented and change a plethora of classes to include the layermask.

**Comment by TotallyGatsby** [comment]
Ok, I think I took @james7132 suggestion. 

Danmaku now have a CollisionMask property (so do DanmakuConfig/State). Then, in DanmakuCollider, I pass that to Physics2D.

I updated DanmakuEmitter to write the correct CollisionMask based on the prefab's Layer. 

I was able to create a test scene where I could toggle which layers the Danmaku collided with using the standard Unity Physics2D collision matrix.

One open question I have is whether I'm deleting something important. There was some code running collision jobs, but approaching the problem this way obviated the need for that. It wasn't super clear whether that code was performing a critical purpose. (e.g. for performance.)

**Comment by james7132** [comment]
The CollideDanmaku job is a fast-pass collision check. It computes the AABB of the full stride of movement done by a bullet. This limits the number of Physics2D calls made by filtering it down to only the ones that have their AABB intersecting a known collider. This is crucial for dealing with high numbers of bullets, especially when they generally are not close to colliders. Please revert its removal.

Other than reverting that change, the defaults for the collision mask aren't too reasonable. The default value for CollisionMask is 0, which means bullets collide with nothing, something that isn't desirable as the default. Here's what I am thinking:

 * Restore the CollidesWith as DefaultCollisionMask, which defaults to a full mask (-1 instead of 0). This would force bullets to collide with everything by default.  Keep this as a LayerMask type instead of int.
 * Set up collision mask on creation of new Danmaku to the pool default.
 * Make CollisionMask in DanmakuState nullable. Assign the mask only if it is not null, otherwise default to the pool default. Change this to LayerMask.
 * Set the pool default to use the DanmakuPrefab's layer mask on creation.

This would allow us to use more sane defaults, and better establish the relationship between DanmakuPrefabs and DanmakuPools: every DanmakuPool created from a DanmakuPrefab will inherit it's layer mask by default, which the developer can override. The current code written only works in the context of DanmakuEmitters.

**Comment by TotallyGatsby** [comment]
Interesting, does Physics2D not do a similar prune/fast out internally? Happy to put it back. 

I'll make the changes you suggested.

**Comment by james7132** [comment]
It's likely calculated on the engine's side, but making that many marshaled calls into native code will inevitably have higher time cost than just doing AABB checks on the managed side.

**Pull request closed without merging**
